apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-dashboard
  namespace: john-dashboard-ui
spec:
  selector:
    matchLabels:
      app: react-dashboard
  replicas: 3  
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react-dashboard
    spec:
      containers:
        - name: react-dashboard
          image: CONTAINER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
